<?php

return [
    'name' => 'User',
    'verification_length' => 5,

    'brands' => [
        "10.or",
        "Apple",
        "Asus",
        "Blackberry",
        "Coolpad",
        "Gionee",
        "Google",
        "Honor",
        "HTC",
        "Huawei",
        "Infinix",
        "InFocus",
        "Intex",
        "Karbonn",
        "Lava",
        "LeEco",
        "Lenovo",
        "LG",
        "Lyf",
        "Micromax",
        "Motorola",
        "Nokia",
        "OnePlus",
        "Oppo",
        "Other",
        "Panasonic",
        "Poco",
        "Realme",
        "Redmi",
        "Samsung",
        "Sony",
        "Tecno",
        "Vivo",
        "Xiaomi",
        "Xolo",
        "Yu",
    ],
];
