theme: jekyll-theme-cayman
title: laravel grid
description: Simple, customizable, pjax ready bootstrap styled grid view for the laravel framework, inspired by the yii2 gridview widget. For laravel 5.5 and above.
